spring.application.name=filesharing
server.port=8080
server.address=0.0.0.0

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# WebSocket config to handle large incoming buffers just in case
server.tomcat.websocket.max-text-message-buffer-size=65536
server.tomcat.websocket.max-binary-message-buffer-size=65536
spring.websocket.max-text-message-size=104857600
spring.websocket.max-binary-message-size=104857600
